CREATE TABLE loan_applications (
    application_id BIGINT PRIMARY KEY,
    age INTEGER,
    gender VARCHAR(20),
    marital_status VARCHAR(30),
    education_level VARCHAR(50),
    employment_status VARCHAR(50),
    job_experience_years NUMERIC(5,2),
    annual_income NUMERIC(15,2),
    monthly_income NUMERIC(15,2),
    credit_score INTEGER,
    credit_history_years NUMERIC(5,2),
    existing_loans INTEGER,
    late_payments_last_2_years INTEGER,
    loan_amount NUMERIC(15,2),
    loan_term_months INTEGER,
    loan_purpose VARCHAR(100),
    interest_rate NUMERIC(6,3),
    debt_to_income_ratio NUMERIC(8,4),
    savings_balance NUMERIC(15,2),
    checking_balance NUMERIC(15,2),
    total_assets NUMERIC(15,2),
    total_liabilities NUMERIC(15,2),
    monthly_debt_payment NUMERIC(15,2),
    property_ownership VARCHAR(50),
    residential_status VARCHAR(50),
    dependents INTEGER,
    co_applicant BOOLEAN,
    collateral VARCHAR(100),
    application_channel VARCHAR(50),
    region VARCHAR(50),
    bank_account_age_years NUMERIC(5,2),
    previous_loan_status VARCHAR(50),
    risk_score NUMERIC(8,2),
    default_risk VARCHAR(12),
    approved_amount NUMERIC(15,2),
    loan_approved VARCHAR (12)
);
